---
version: "3.9"

services:
  python27:
    build:
      context: .
      dockerfile: common.Dockerfile
      args:
        PYTHON_VERSION_SET: 2.7
    entrypoint: /bin/bash -c "/root/ibm_zos_cics/ansible_collections/ibm/ibm_zos_cics/container.build.sh"
    volumes:
      - ./:/root/ibm_zos_cics/ansible_collections/ibm/ibm_zos_cics

  python38:
    build:
      context: .
      dockerfile: common.Dockerfile
      args:
        PYTHON_VERSION_SET: 3.8
    entrypoint: /bin/bash -c "/root/ibm_zos_cics/ansible_collections/ibm/ibm_zos_cics/container.build.sh"
    volumes:
      - ./:/root/ibm_zos_cics/ansible_collections/ibm/ibm_zos_cics

  python39:
    build:
      context: .
      dockerfile: common.Dockerfile
      args:
        PYTHON_VERSION_SET: "3.9"
    entrypoint: /bin/bash -c "/root/ibm_zos_cics/ansible_collections/ibm/ibm_zos_cics/container.build.sh"
    volumes:
      - ./:/root/ibm_zos_cics/ansible_collections/ibm/ibm_zos_cics

  python310:
    build:
      context: .
      dockerfile: common.Dockerfile
      args:
        PYTHON_VERSION_SET: "3.10"
    entrypoint: /bin/bash -c "/root/ibm_zos_cics/ansible_collections/ibm/ibm_zos_cics/container.build.sh"
    volumes:
      - ./:/root/ibm_zos_cics/ansible_collections/ibm/ibm_zos_cics

  python311:
    build:
      context: .
      dockerfile: common.Dockerfile
      args:
        PYTHON_VERSION_SET: "3.11"
    entrypoint: /bin/bash -c "/root/ibm_zos_cics/ansible_collections/ibm/ibm_zos_cics/container.build.sh"
    volumes:
      - ./:/root/ibm_zos_cics/ansible_collections/ibm/ibm_zos_cics
